---
- name: Install and configure nginx from source
  become: true
  apt:
    name:
      - build-essential 
      - libpcre3 
      - libpcre3-dev 
      - zlib1g-dev 
      - libssl-dev

- name: Download nginx tar file with specific version
  become: true
  get_url:
    url: "https://nginx.org/download/nginx-{{ nginx_version }}.tar.gz"
    dest: "/tmp/nginx-{{ nginx_version }}.tar.gz"
    owner: root
    group: root
    mode: "0755"

- name: Create directory to extract the tar file
  become: true
  file:
    path: /loadbalancer
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Extract the tar file
  become: true
  unarchive:
    src: "/tmp/nginx-{{ nginx_version }}.tar.gz"
    dest: /loadbalancer
    remote_src: true

- name: Configure the nginx
  become: true
  shell: |
    cd /loadbalancer/nginx-{{ nginx_version}}
    ./configure \
    --prefix=/etc/nginx \
    --conf-path=/etc/nginx/nginx.conf \
    --error-log-path=/var/log/nginx/error.log \
    --http-log-path=/var/log/nginx/access.log \
    --pid-path=/run/nginx.pid \
    --sbin-path=/usr/sbin/nginx \
    --with-http_ssl_module \
    --with-http_v2_module \
    --with-http_stub_status_module \
    --with-http_realip_module \
    --with-file-aio \
    --with-threads \
    --with-stream \
    --with-stream_ssl_preread_module
    make && make install

- name: Create systemd file for nginx
  become: true
  template:
    src: nginx.service.j2
    dest: /etc/systemd/system/nginx.service
    mode: "0644"
  notify: Systemd reload

- name: Start and enable nginx service
  become: true
  service:
    name: nginx.service
    state: started
    enabled: true
...
